[package]
name = "icaro"
version = "0.2.0"
description = "I.C.A.R.O. — RPG open source de evolução pessoal"
authors = ["tombemol"]
edition = "2021"

[lib]
name = "icaro_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
